#### click article like
POST localhost:8080/articleLike/like/472e4b35-0815-441f-bf8c-0c07144d8743
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgyNzcyNDgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MzYzNjQ4LCJpc3MiOiJLdW5VelRlc3QifQ.kpkIXa1TS5toD1MEvKawiU2RVqhd4-NbsLKEzbpGMQvT0alkQ6s9-HJv7oE8FGXYWzT7wJ1lwM7oHs5B0XwBdg

#### click article dislike
POST localhost:8080/articleLike/dislike/472e4b35-0815-441f-bf8c-0c07144d8743
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgyNzcyNDgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MzYzNjQ4LCJpc3MiOiJLdW5VelRlc3QifQ.kpkIXa1TS5toD1MEvKawiU2RVqhd4-NbsLKEzbpGMQvT0alkQ6s9-HJv7oE8FGXYWzT7wJ1lwM7oHs5B0XwBdg

#### click article remove
PUT localhost:8080/articleLike/remove/472e4b35-0815-441f-bf8c-0c07144d8743
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgyNzcyNDgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MzYzNjQ4LCJpc3MiOiJLdW5VelRlc3QifQ.kpkIXa1TS5toD1MEvKawiU2RVqhd4-NbsLKEzbpGMQvT0alkQ6s9-HJv7oE8FGXYWzT7wJ1lwM7oHs5B0XwBdg