#### click article like
POST localhost:8080/articleLike/like/ce0cdd7d-ffa3-40a6-8179-8d7747c126e7
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTU4MTcsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAyMjE3LCJpc3MiOiJLdW5VelRlc3QifQ.sODrn8DKbrGl8Nsb-aqqv40UuO4jHeXAHCrPZxiqoTz3HGlxQ0zIe-A4M2zq6ynZ-ye5MtVntgNfSWMUMdXxUQ

#### click article dislike
POST localhost:8080/articleLike/dislike/ce0cdd7d-ffa3-40a6-8179-8d7747c126e7
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTU4MTcsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAyMjE3LCJpc3MiOiJLdW5VelRlc3QifQ.sODrn8DKbrGl8Nsb-aqqv40UuO4jHeXAHCrPZxiqoTz3HGlxQ0zIe-A4M2zq6ynZ-ye5MtVntgNfSWMUMdXxUQ

#### click article remove
PUT localhost:8080/articleLike/remove/ce0cdd7d-ffa3-40a6-8179-8d7747c126e7
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTU4MTcsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAyMjE3LCJpc3MiOiJLdW5VelRlc3QifQ.sODrn8DKbrGl8Nsb-aqqv40UuO4jHeXAHCrPZxiqoTz3HGlxQ0zIe-A4M2zq6ynZ-ye5MtVntgNfSWMUMdXxUQ