### Create photo or vidio or mp3
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="vidio.mp4"

< C:\Users\Aslbek\Desktop\Teskshirish\sv.mp4

### Get photo and mp3 and mp4  --bu faqat projectni uploads file ichidagi malumotni oqiy oladi
GET localhost:8080/attach/open/1055746b-e91e-4747-a0a2-297d66279072.jpg

### Get photo and mp3 and mp4   -- bu faqat projectni attaches  file ni ichidagi malumotni oqiy oladi
GET localhost:8080/attach/open_general/c82ee70a-c1f6-49ac-9493-491f353d06fa.mp3

###  Get by pagination
GET localhost:8080/attach/open_general/pagination?page=1&size=3

### Delete data by id - yani id boyicha fayldagi malumotni o'chirish.
DELETE localhost:8080/attach/delete/1f8db80f-3da9-4c43-bd57-49ecda8b1a73
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcxMzQyOTQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDcyMjA2OTQsImlzcyI6Ikt1blV6VGVzdCJ9.7j2Viq0RO9fB96MSUc19yQd8fDD-1WngvaxFK1ddoefUKKV0RuFaqd-Nh2lv-AIB9-KHa2r25Xbbu0fjkU3n4A

### sava image
GET http://localhost:8080/attach/download/6040d2d8-1d7e-44d7-93c7-9d9271c70c2f.jpg