### create category
POST localhost:8080/category/adm
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzE5OTgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE4Mzk4LCJpc3MiOiJLdW5VelRlc3QifQ.247HOV79ug_rBOyaXt1SHp1Rm03quoIdfUnbvHRGDnstFcp3lYxoOcWIwNATJCrq0P0igIzFrFbY09P0Brnfeg

{
  "name_en": "Economy",
  "name_uz": "Iqtisodiyot",
  "name_ru": "Экономика",
  "order_number": 2
}

###Update category
PUT localhost:8080/category/adm/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzE5OTgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE4Mzk4LCJpc3MiOiJLdW5VelRlc3QifQ.247HOV79ug_rBOyaXt1SHp1Rm03quoIdfUnbvHRGDnstFcp3lYxoOcWIwNATJCrq0P0igIzFrFbY09P0Brnfeg

{
  "order_number": 3
}

### Delete category
DELETE localhost:8080/category/adm/2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzE5OTgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE4Mzk4LCJpc3MiOiJLdW5VelRlc3QifQ.247HOV79ug_rBOyaXt1SHp1Rm03quoIdfUnbvHRGDnstFcp3lYxoOcWIwNATJCrq0P0igIzFrFbY09P0Brnfeg

### Get all category
GET localhost:8080/category/adm
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzE5OTgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE4Mzk4LCJpc3MiOiJLdW5VelRlc3QifQ.247HOV79ug_rBOyaXt1SHp1Rm03quoIdfUnbvHRGDnstFcp3lYxoOcWIwNATJCrq0P0igIzFrFbY09P0Brnfeg

### Get lang category
GET localhost:8080/category/adm/lang?lang=RU
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzE5OTgsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE4Mzk4LCJpc3MiOiJLdW5VelRlc3QifQ.247HOV79ug_rBOyaXt1SHp1Rm03quoIdfUnbvHRGDnstFcp3lYxoOcWIwNATJCrq0P0igIzFrFbY09P0Brnfeg

