### click comment like Api
POST localhost:8080/commentLike/like/3
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQyNDksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNjQ5LCJpc3MiOiJLdW5VelRlc3QifQ.FLKcKct3gen0-HoeS7r5_FjU4ohnC1PLu9y1tGvKINmeHoJT8MMSr2fjn9R2B0B8Au4jdI7Z7frxGH6cvq_ZLA

### click comment dislike Api
POST localhost:8080/commentLike/dislike/2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQyNDksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNjQ5LCJpc3MiOiJLdW5VelRlc3QifQ.FLKcKct3gen0-HoeS7r5_FjU4ohnC1PLu9y1tGvKINmeHoJT8MMSr2fjn9R2B0B8Au4jdI7Z7frxGH6cvq_ZLA

### click comment like remove Api
PUT localhost:8080/commentLike/remove/2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQyNDksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNjQ5LCJpc3MiOiJLdW5VelRlc3QifQ.FLKcKct3gen0-HoeS7r5_FjU4ohnC1PLu9y1tGvKINmeHoJT8MMSr2fjn9R2B0B8Au4jdI7Z7frxGH6cvq_ZLA
