### Post profile
POST localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc1NjYzMzUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc2NTI3MzUsImlzcyI6Ikt1blV6VGVzdCJ9.0zGw9r6JwExADazjP2GHBpuccdperIdpiz2nqDU7RPmF1JtsOBzKnDTXRepZPByWNJsiV1tmabClIZ5bF7ErDQ

{
  "name": "Aslbek",
  "surname": "Norqulov",
  "phone": "+998369920747",
  "email": "xxxxsps@gmail.com",
  "password": "123",
  "status": "ACTIVE",
  "role": "ADMIN"
}

### Update profile Admin
PUT localhost:8080/profile/adm/update?id=8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MzQyMzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjA2MzYsImlzcyI6Ikt1blV6VGVzdCJ9.8cwhfDhPNJH0rrFhnIHEHdfUnRiPNA7Qx1UGlvNBKsvS_KCAwMMYynpRtqrYK1YtbkNxFzdJs97X7kevpCEybQ

{
  "role": "ADMIN"
}

###  Update profile User
PUT localhost:8080/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0Mzk4NjgsImlkIjoyMCwicm9sZSI6IlVTRVIiLCJleHAiOjE3MDY1MjYyNjgsImlzcyI6Ikt1blV6VGVzdCJ9.mJg4yQ1MpJBrRdjJ4tst50fxoLFQacjXBLklM50UdvKPRAE8KXQw1j8vIwRYZowiZUmb4tklsWszRsB-Ozckzw

{
  "name": "AslWW"
}


### Delete profile
DELETE localhost:8080/profile/adm/delete?id=8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MzQyMzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjA2MzYsImlzcyI6Ikt1blV6VGVzdCJ9.8cwhfDhPNJH0rrFhnIHEHdfUnRiPNA7Qx1UGlvNBKsvS_KCAwMMYynpRtqrYK1YtbkNxFzdJs97X7kevpCEybQ

### Profile All paginable
GET localhost:8080/profile/adm/all?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MzQyMzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjA2MzYsImlzcyI6Ikt1blV6VGVzdCJ9.8cwhfDhPNJH0rrFhnIHEHdfUnRiPNA7Qx1UGlvNBKsvS_KCAwMMYynpRtqrYK1YtbkNxFzdJs97X7kevpCEybQ

### get filter profile
GET localhost:8080/profile/adm/filter?page=1&size=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MzQyMzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjA2MzYsImlzcyI6Ikt1blV6VGVzdCJ9.8cwhfDhPNJH0rrFhnIHEHdfUnRiPNA7Qx1UGlvNBKsvS_KCAwMMYynpRtqrYK1YtbkNxFzdJs97X7kevpCEybQ

{
  "role": "ADMIN"
}
