### Post profile --> Admin  MODERATOR YOKI PUBLISHER ni qolda kiritadi,keyin osha moderator admin kiritgan login va paroli bilan saytga qayta login qilib kira oladi
POST localhost:8080/profile/adm
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjA4NzksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3Mjc5LCJpc3MiOiJLdW5VelRlc3QifQ.HQrYXGcgddg7_q7EZWnuF2QImOcWjKaS2dPKGECli47cvk49SmxbuFPyn0vpUIyCyYdxrKGuIllOXQPQZNBWEQ

{
  "name": "Shamshod",
  "surname": "Salomov",
  "phone": "+998991205577",
  "email": "shamshod12@gmail.com",
  "password": "1234",
  "status": "ACTIVE",
  "role": "ROLE_MODERATOR"
}

### Update profile Admin --> Admin hohlagan profile ni malumotlarini o'zgarish uchun yozilgan api
PUT localhost:8080/profile/adm/update?id=4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjQxODcsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTEwNTg3LCJpc3MiOiJLdW5VelRlc3QifQ.HKfxuNmDyVtVmLJ7KM00TZEikAXCjrUjrreIsPAid2M_IWiagFdMUHqc9F3Ts_W7ALD_IKTf6GJbXXkixZd5cQ

{
  "role": "ROLE_MODERATOR"
}

###  Update profile User --> User,Moderator,Publisher faqat ozlarini malumotlarini o'zgartirish uchun yozilgan api
PUT localhost:8080/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjQzOTIsImVtYWlsIjoicmFqYWJvbGxhbmF6YXJvdkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NT0RFUkFUT1IiLCJleHAiOjE3MDc5MTA3OTIsImlzcyI6Ikt1blV6VGVzdCJ9.PNie6yklkW4nF420HcUkm965FYjFk4ekXcW3R3QBBR0W8JEdch0cyd4o5E469yNyIgBLLqbod8JbzRD_TaJPrA

{
  "surname": "Ollanazarov"
}

### Delete profile --> Admin hohlagan profileni ochira oladi, bu api ham adminga hohlagan profileni ochira olishi uchun yozilgan
DELETE localhost:8080/profile/adm/delete?id=4
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjA4NzksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3Mjc5LCJpc3MiOiJLdW5VelRlc3QifQ.HQrYXGcgddg7_q7EZWnuF2QImOcWjKaS2dPKGECli47cvk49SmxbuFPyn0vpUIyCyYdxrKGuIllOXQPQZNBWEQ

### Profile All paginable --> Admin profilelar ro'yhatini page lab yani sahifalab ko'rishi uchun yozilgan api
GET localhost:8080/profile/adm/all?page=1&size=2
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjA4NzksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3Mjc5LCJpc3MiOiJLdW5VelRlc3QifQ.HQrYXGcgddg7_q7EZWnuF2QImOcWjKaS2dPKGECli47cvk49SmxbuFPyn0vpUIyCyYdxrKGuIllOXQPQZNBWEQ

### get filter profile --> Admin profilelar ro'yhatini filterlab misol uchun ismi boyicha yoki no'meri bo'yicha filtirlab sahifalab yani page lab kora olishi uchun yozilgan api
GET localhost:8080/profile/adm/filter?page=1&size=3
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjA4NzksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3Mjc5LCJpc3MiOiJLdW5VelRlc3QifQ.HQrYXGcgddg7_q7EZWnuF2QImOcWjKaS2dPKGECli47cvk49SmxbuFPyn0vpUIyCyYdxrKGuIllOXQPQZNBWEQ

{
  "role": "ROLE_ADMIN"
}
