### Create (ANY)
POST localhost:8080/savedArticle/81ba32b6-603a-4826-8188-ecf43f03d09b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0ODEyMzUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA5NTY3NjM1LCJpc3MiOiJLdW5VelRlc3QifQ.iel7YOhxM41WGTUrrHntI-N6uA1H2ggU6q2C3bjxSrmprcYArm7vU5WtWpS0jUjqNr5QF_DYqlu0cK7IW3DWnA

### delete (any)
DELETE localhost:8080/savedArticle/81ba32b6-603a-4826-8188-ecf43f03d09b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0ODEyMzUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA5NTY3NjM1LCJpc3MiOiJLdW5VelRlc3QifQ.iel7YOhxM41WGTUrrHntI-N6uA1H2ggU6q2C3bjxSrmprcYArm7vU5WtWpS0jUjqNr5QF_DYqlu0cK7IW3DWnA

### Get Profile Saved Article List (ANY)
GET localhost:8080/savedArticle/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0ODQ2NzUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA5NTcxMDc1LCJpc3MiOiJLdW5VelRlc3QifQ.9LNgkPH5kOMntRwuiFqC72O8_HTujuyfwyhJ1HpgcwluST_6hspfHL6hFZQaCdXzkH1VBwe1Oo4CdYwglCISJA
# (id,article(id,title,description,image(id,url)))