###  get by phone  --> Admin sms yuborilgan no'merlarni history sini ko'rish uchun yozilgan api
POST localhost:8080/sms_history/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4Mjg5ODUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE1Mzg1LCJpc3MiOiJLdW5VelRlc3QifQ.-t8QE2DFahw2bpaeikkLfJFcz4RMdbpGA8_c9pbahZ25nVMUepgKS7xN7QxJtuOGiLPvoGOCYQeEP3lMc0XOlA

{
  "phone": "+998934569540"
}

### get by date --> Admin qaysi vaqtda kimga nechta sms yuborganini kora olish uchun yozilgan api
GET localhost:8080/sms_history/adm/2024-02-13
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4Mjg5ODUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE1Mzg1LCJpc3MiOiJLdW5VelRlc3QifQ.-t8QE2DFahw2bpaeikkLfJFcz4RMdbpGA8_c9pbahZ25nVMUepgKS7xN7QxJtuOGiLPvoGOCYQeEP3lMc0XOlA

### get pagination --> Admin sms lar history larini page lab olish uchun yozilgan api
GET localhost:8080/sms_history/adm/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4Mjg5ODUsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTE1Mzg1LCJpc3MiOiJLdW5VelRlc3QifQ.-t8QE2DFahw2bpaeikkLfJFcz4RMdbpGA8_c9pbahZ25nVMUepgKS7xN7QxJtuOGiLPvoGOCYQeEP3lMc0XOlA
