###  get by phone
POST localhost:8080/sms_history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4NjMwODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NDk0ODQsImlzcyI6Ikt1blV6VGVzdCJ9.7LwzDygC8i5LKX28828rgj_v-SDI4Lx2N6G9zxk2ok-fsRod_oDlUqBOvZLs7Xcn0MQ-dxGXR_Q1-jYMyqqbQQ

{
  "phone": "+998991205577"
}

### get by date
GET localhost:8080/sms_history/2024-02-02
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4NjMwODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NDk0ODQsImlzcyI6Ikt1blV6VGVzdCJ9.7LwzDygC8i5LKX28828rgj_v-SDI4Lx2N6G9zxk2ok-fsRod_oDlUqBOvZLs7Xcn0MQ-dxGXR_Q1-jYMyqqbQQ

### get pagination
GET localhost:8080/sms_history/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4NjMwODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NDk0ODQsImlzcyI6Ikt1blV6VGVzdCJ9.7LwzDygC8i5LKX28828rgj_v-SDI4Lx2N6G9zxk2ok-fsRod_oDlUqBOvZLs7Xcn0MQ-dxGXR_Q1-jYMyqqbQQ
